---
title: "Collection of Datasets and Research Questions"
output: html_notebook
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytuesdayR)
```


```{r}
#Data is about passwords in general

passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')

# Or read in with tidytuesdayR package (https://github.com/thebioengineer/tidytuesdayR)
# PLEASE NOTE TO USE 2020 DATA YOU NEED TO UPDATE tidytuesdayR from GitHub

# Either ISO-8601 date or year/week works!

# Install via devtools::install_github("thebioengineer/tidytuesdayR")

tuesdata <- tidytuesdayR::tt_load('2020-01-14') 
tuesdata <- tidytuesdayR::tt_load(2020, week = 3)

#Potential Research Questions
#Does category of password affect the time it takes to crack password (online or offline)
#Most popular letters used in passwords

```

```{r}
#Data gives us percentages of fatal collisions of drivers doing some illegal activity (drinking, etc.)

bad_drivers <- readr::read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/bad-drivers/bad-drivers.csv')

#Potential Research Questions: 
#States with the most bad drives...this was actually a question in 538 but we can do our own statistics/graphs about it..not sure though seems like an interesting question.
#Common causes of fatal colllisions in each state

```

```{r}
#Think this one is my favorite dataset with potential for good/applicable research questions 
hate_crimes <- readr::read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/hate-crimes/hate_crimes.csv')

#Potential Research Questions
#Association between household income and percentage of hate crimes
#What can the GINI Index tell us about hate crimes in an area?
#Does having a high school degree affect average median household income?
```

```{r}
# 2008 - 2014 US Suicides Rates per 100,000 Population
# All injury, suicide, all races, all ethnicities, both sexes, all ages. annualized crude rate for united states: 12.63
# The main thing I'm looking at.
opioid_and_suicide_rate <- read_csv('https://raw.githubusercontent.com/qiqiliang/statistics/master/US_Suicide_and_Opioid_Prescription_Rates')

# Suicide Rate average between 2008 and 2014 per 100,000 people

# Opioid Prescription Rate average between 2005 and 2015 per 100 US Residents 
##############################################################################################################
# optional content
##############################################################################################################


# Suicide Mortality by State
# this one is less important
suicide_mortality <- read.csv('https://raw.githubusercontent.com/qiqiliang/statistics/master/Suicide_Mortality_by_State.csv')

# VSRR Provisional Drug Overdose Death Counts
# Not the main thing I'm looking at.
overdose_death <- read.csv('https://raw.githubusercontent.com/qiqiliang/statistics/master/VSRR_Provisional_Drug_Overdose_Death_Counts.csv')

#Potential Research Questions
#Association between opioid prescription rate and suicide rate.
#Can we do an overlay of the two maps??
#Does a larger rate of legal opioid prescription cause a higher rate of overdoses and suicides?
```





