---
title: "a bunch of different data"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytuesdayR)
knitr::opts_chunk$set(echo = TRUE)

# #installing stuff with ggmap
# if(!requireNamespace("devtools")) install.packages("devtools")
# devtools::install_github("dkahle/ggmap", ref = "tidyup", force=TRUE)
# #loading library
# library("ggmap")
# #Set your API Key
# ggmap::register_google(key = "SET YOUR KEY HERE")


# https://github.com/rfordatascience/tidytuesday
```



```{r}

ramen_ratings <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-04/ramen_ratings.csv")

meteorites <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-11/meteorites.csv")

nuclear_explosions <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-20/nuclear_explosions.csv")

# traumatic brain injuries

tbi_age <- read.csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-24/tbi_age.csv')

tbi_year <- read.csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-24/tbi_year.csv')

tbi_military <- read.csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-24/tbi_military.csv')

# Get the Data

polls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-14/polls.csv')
rankings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-14/rankings.csv')

# Or read in with tidytuesdayR package (https://github.com/thebioengineer/tidytuesdayR)
# PLEASE NOTE TO USE 2020 DATA YOU NEED TO USE tidytuesdayR version from GitHub

# Either ISO-8601 date or year/week works!

# Install via devtools::install_github("thebioengineer/tidytuesdayR")

tuesdata <- tidytuesdayR::tt_load('2020-04-14')
tuesdata <- tidytuesdayR::tt_load(2020, week = 16)


polls <- tuesdata$polls
```

```{r}
# 2008 - 2014 US Suicides Rates per 100,000 Population
# All injury, suicide, all races, all ethnicities, both sexes, all ages. annualized crude rate for united states: 12.63
suicides <- read.csv('https://wisqars.cdc.gov:8443/cdcMapFramework/ExcelServlet?excelFile=m4687721_csv')

suicides <- suicides %>%
  slice(22:3159) %>%
  select(- X_)

```

```{r}
# Suicide Mortality by State
suicide_mortality <- read.csv('https://raw.githubusercontent.com/qiqiliang/statistics/master/Suicide_Mortality_by_State.csv')
```

```{r}
# Opioid Prescribing Rate by County

opioid_prescription_rate <- read.csv('https://raw.githubusercontent.com/qiqiliang/statistics/master/US_County_Prescribing_Rates_Opioids.csv')
```

```{r}
# VSRR Provisional Drug Overdose Death Counts

overdose_death <- read.csv('https://raw.githubusercontent.com/qiqiliang/statistics/master/VSRR_Provisional_Drug_Overdose_Death_Counts.csv')
```





